development:  
  adapter: postgresql
  encoding: unicode
  database: 
  pool: 5
  username: seanburke
  password:

test:  
  adapter: postgresql
  encoding: unicode
  database: 
  pool: 5
  username: seanburke
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: 
  pool: 5
  username: seanburke
  password:
